/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vue;

import coucheDAO.EditionDAO;
import coucheDAO.EquipeDAO;
import edition.Edition;
import equipe.Equipe;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Landry 
 */
public class Affiche1_Equipe extends javax.swing.JFrame {

    /**
     * Creates new form Affiche1_Equipe
     */
    public Affiche1_Equipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Felix Titling", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(12, 229, 98));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        jButton1.setText("Afficher l'effectif");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        jButton2.setText("Afficher le Staff");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        jButton3.setText("Constitution de l'Equipe");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        jLabel1.setText("Listes des Equipes ayant participé l'édition:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caf - Copy.gif"))); // NOI18N

        jButton4.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        jButton4.setText("Fermer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cb1.setFont(new java.awt.Font("DigifaceWide", 0, 12)); // NOI18N
        try{
            EditionDAO editionDAO = new EditionDAO();
            ArrayList<Edition> edition = new ArrayList<>();
            edition = editionDAO.trouve();

            for(Edition ed : edition){
                cb1.addItem(ed.getAnnee());
            }
        }catch(SQLException ex){
            //Logger.getLogger(CreationJoueur.class.getName()).log(Level.SEVERE,null,ex);
        }
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(55, 55, 55)))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51)
                        .addComponent(jButton2)
                        .addGap(52, 52, 52)
                        .addComponent(jButton3)
                        .addGap(46, 46, 46)
                        .addComponent(jButton4)
                        .addGap(5, 5, 5)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Effectif_Equipe fen = new Effectif_Equipe();
        fen.setVisible(true);
        fen.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Staff_Equipe fen = new Staff_Equipe();
        fen.setVisible(true);
        fen.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Fiche_Equipe fen = new Fiche_Equipe();
        fen.setVisible(true);
        fen.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        try{
                EditionDAO editionDAO = new EditionDAO();
                Edition edition = editionDAO.cherche((String)cb1.getSelectedItem()); 
                EquipeDAO eqDAO = new EquipeDAO();
                ArrayList<Equipe> equipe = new ArrayList<>();
                equipe = eqDAO.chercher(edition.getId());
                ArrayList<Edition> ediEquip = new ArrayList<>();
                ediEquip = eqDAO.editionJouer(equipe.get(0).getNom());
                if (equipe.size() == 16){
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                            {equipe.get(0).getNom(), equipe.get(0).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(0).getNom()))},
                            {equipe.get(1).getNom(), equipe.get(1).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(1).getNom()))},
                            {equipe.get(2).getNom(), equipe.get(2).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(2).getNom()))},
                            {equipe.get(3).getNom(), equipe.get(3).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(3).getNom()))},
                            {equipe.get(4).getNom(), equipe.get(4).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(4).getNom()))},
                            {equipe.get(5).getNom(), equipe.get(5).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(5).getNom()))},
                            {equipe.get(6).getNom(), equipe.get(6).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(6).getNom()))},
                            {equipe.get(7).getNom(), equipe.get(7).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(7).getNom()))},
                            {equipe.get(8).getNom(), equipe.get(8).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(8).getNom()))},
                            {equipe.get(9).getNom(), equipe.get(9).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(9).getNom()))},
                            {equipe.get(10).getNom(), equipe.get(10).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(10).getNom()))},
                            {equipe.get(11).getNom(), equipe.get(11).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(11).getNom()))},
                            {equipe.get(12).getNom(), equipe.get(12).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(12).getNom()))},
                            {equipe.get(13).getNom(), equipe.get(13).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(13).getNom()))},
                            {equipe.get(14).getNom(), equipe.get(14).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(14).getNom()))},
                            {equipe.get(15).getNom(), equipe.get(15).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(15).getNom()))},
                            },
                        new String [] {
                            "Listes des Equipes", "Nombre de participations", "Editions Gagnées"}
                ) );
                }
                else if (equipe.size() == 1){
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                            {equipe.get(0).getNom(), equipe.get(0).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(0).getNom()))},
                            },
                        new String [] {
                            "Listes des Equipes", "Nombre de participations", "Editions Gagnées"}
                ) );
                }
                else if (equipe.size() == 2){
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                            {equipe.get(0).getNom(), equipe.get(0).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(0).getNom()))},
                            {equipe.get(1).getNom(), equipe.get(1).getNbPar(),  eqDAO.victoire(eqDAO.editionGagnee(equipe.get(1).getNom()))},
                            },
                        new String [] {
                            "Listes des Equipes", "Nombre de participations", "Editions Gagnées"}
                ) );
                }
            }catch(SQLException ex){
                 Logger.getLogger(CreationJoueur.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_cb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Affiche1_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Affiche1_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Affiche1_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Affiche1_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Affiche1_Equipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
