/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vue;

import coucheDAO.EditionDAO;
import coucheDAO.PouleDAO;
import edition.Edition;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author Landry
 */
public class CreationEdition extends javax.swing.JFrame {

    /**
     * Creates new form Edition
     */
    public CreationEdition() {
        initComponents();
         lb4.setVisible(false);
         cb3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lb2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rb2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        cb2 = new javax.swing.JComboBox();
        cb3 = new javax.swing.JComboBox();
        bt2 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        lb4 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creation d'une nouvelle Edition");
        setBackground(new java.awt.Color(0, 204, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lb2.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        lb2.setText("Nombre");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caf - Copy.gif"))); // NOI18N

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        rb2.setText("2");
        rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        rb1.setSelected(true);
        rb1.setText("1");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        cb2.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afrique du Sud", "Algérie", "Angola", "Bénin", "Burkina Faso", "Burundi", "Botwana", "Cameroun", "Cap-Vert", "Comores", "Côte d'Ivoire", "Djibouti", "Egypte", "Erythrée", "Gabon", "Gambie", "Ghana", "Guinnée", "Guinnée B", "Guinnée E.", "Kenya", "Liberia", "Lybie", "Madagascar", "Malawi", "Mali", "Maroc", "Maurice", "Mozambique", "Niger", "Nigeria", "RCA", "RDC", "Sao Tomé", "Sénégal", "Soudan", "Tchad", "Togo", "Tunisie", "Zambie", "Zimbabwé" }));

        cb3.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afrique du Sud", "Algérie", "Angola", "Bénin", "Burkina Faso", "Burundi", "Botwana", "Cameroun", "Cap-Vert", "Comores", "Côte d'Ivoire", "Djibouti", "Egypte", "Erythrée", "Gabon", "Gambie", "Ghana", "Guinnée", "Guinnée B", "Guinnée E.", "Kenya", "Liberia", "Lybie", "Madagascar", "Malawi", "Mali", "Maroc", "Maurice", "Mozambique", "Niger", "Nigeria", "RCA", "RDC", "Sao Tomé", "Sénégal", "Soudan", "Tchad", "Togo", "Tunisie", "Zambie", "Zimbabwé" }));

        bt2.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        bt2.setText("Continuer");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt1.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        bt1.setText("Annuler");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        lb4.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        lb4.setText("Pays");

        lb3.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        lb3.setText("Pays");

        jLabel2.setFont(new java.awt.Font("DigifaceWide", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 163, 53));
        jLabel2.setText("Nouvelle Edition");

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Pays Organisateurs");

        lb5.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        lb5.setText("Annee :");

        jTextField1.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lb5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb3)
                                        .addComponent(lb4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lb2))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb1)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb2)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt1)
                                .addGap(27, 27, 27)
                                .addComponent(bt2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb1)
                        .addComponent(lb2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb3)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb4)
                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt2)
                    .addComponent(bt1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
        lb4.setVisible(false);
        cb3.setVisible(false);
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
        lb4.setVisible(true);
        cb3.setVisible(true);
    }//GEN-LAST:event_rb2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        try {
            // TODO add your handling code here:
            Edition edition = new Edition();
            EditionDAO editionDAO = new EditionDAO();
            PouleDAO pouleDAO = new PouleDAO();
            String nom_ed = (String)jTextField1.getText();
            if(!editionDAO.editionDejaCree(editionDAO.cherche(nom_ed).getAnnee())){
                edition.setAnnee((String)jTextField1.getText());
                if(editionDAO.verifEditionTermine(editionDAO.cherche().getId()) == true){
                    if (rb1.isSelected() == true){
                        edition.setPaysOrg((String)cb2.getSelectedItem());
                        edition = editionDAO.creer(edition.getAnnee(), edition.getPaysOrg());
                        editionDAO.creerPouleEdition("A", edition.getId());
                        pouleDAO.creer((String)cb2.getSelectedItem(),"A", edition.getId());
                        editionDAO.creerPouleEdition("B", edition.getId());
                        editionDAO.creerPouleEdition("C", edition.getId());
                        editionDAO.creerPouleEdition("D", edition.getId());

                        editionDAO.creerQuartEdition("1A-2B", edition.getId());
                        editionDAO.creerQuartEdition("1B-2A", edition.getId());
                        editionDAO.creerQuartEdition("1C-2D", edition.getId());
                        editionDAO.creerQuartEdition("1D-2C", edition.getId());

                        editionDAO.creerDemiEdition("Vainqueur 1A-2B/1C-2D", edition.getId());
                        editionDAO.creerDemiEdition("Vainqueur 1B-2A/1D-2C", edition.getId());

                        editionDAO.creerPfinalEdition("Perdant 1A-2B/1C-2D vs 1B-2A/1D-2C", edition.getId());
                        editionDAO.creerFinalEdition("Vainqueur 1A-2B/1C-2D vs 1B-2A/1D-2C", edition.getId());
                        JOptionPane.showMessageDialog(null, "L'edition "+edition.getAnnee()+" organise par "+edition.getPaysOrg()+" a été bien enregistré");
                    }
                    else {
                        if(!cb2.getSelectedItem().equals(cb3.getSelectedItem())){
                            edition.setPaysOrg((String)cb2.getSelectedItem() +"-"+ (String)cb3.getSelectedItem());
                            edition = editionDAO.creer(edition.getAnnee(), edition.getPaysOrg());
                            editionDAO.creerPouleEdition("A", edition.getId());
                            pouleDAO.creer((String)cb2.getSelectedItem(),"A", edition.getId());
                            editionDAO.creerPouleEdition("B", edition.getId());
                            editionDAO.creerPouleEdition("C", edition.getId());
                            pouleDAO.creer((String)cb3.getSelectedItem(),"C", edition.getId());
                            editionDAO.creerPouleEdition("D", edition.getId());

                            editionDAO.creerQuartEdition("1A-2B", edition.getId());
                            editionDAO.creerQuartEdition("1B-2A", edition.getId());
                            editionDAO.creerQuartEdition("1C-2D", edition.getId());
                            editionDAO.creerQuartEdition("1D-2C", edition.getId());

                            editionDAO.creerDemiEdition("Vainqueur 1A-2B/1C-2D", edition.getId());
                            editionDAO.creerDemiEdition("Vainqueur 1B-2A/1D-2C", edition.getId());

                            editionDAO.creerPfinalEdition("Perdant 1A-2B/1C-2D vs 1B-2A/1D-2C", edition.getId());
                            editionDAO.creerFinalEdition("Vainqueur 1A-2B/1C-2D vs 1B-2A/1D-2C", edition.getId());
                            JOptionPane.showMessageDialog(null, "L'edition "+edition.getAnnee()+" organise par "+edition.getPaysOrg()+" a été bien enregistré");
                        }else{
                            JOptionPane.showMessageDialog(null, "Erreur!!! L'equipe est inscrite 2 fois ");
                        }
                    }

                }else if (editionDAO.verifEditionTermine(editionDAO.cherche().getId()) == false){
                    JOptionPane.showMessageDialog(null, "L'edition en cours n'est pas terminée! Veillez l'achever avant de commencer une nouvelle ");
                }
            }else if(editionDAO.editionDejaCree(editionDAO.cherche(nom_ed).getAnnee())){
                JOptionPane.showMessageDialog(null, "L'année inscrite pour l'édition est déja enregistrée pour une autre");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CreationEdition.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_bt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreationEdition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreationEdition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreationEdition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreationEdition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreationEdition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    // End of variables declaration//GEN-END:variables
}
