/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vue;

import coucheDAO.EditionDAO;
import coucheDAO.EquipeDAO;
import coucheDAO.JoueurDAO;
import edition.Edition;
import equipe.Equipe;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import personnel.Joueur;

/**
 *
 * @author Landry
 */
public class Effectif_Equipe extends javax.swing.JFrame {

    /**
     * Creates new form Effectif_Equipe
     */
    public Effectif_Equipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("Effectif ");

        jLabel1.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        jLabel1.setText("Edition");

        jLabel2.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        jLabel2.setText("Equipe");

        cb1.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        try{
            EditionDAO editionDAO = new EditionDAO();
            ArrayList<Edition> edition = new ArrayList<>();
            edition = editionDAO.trouve();

            for(int i = 0; i < edition.size(); i++){
                cb1.addItem(edition.get(i).getAnnee());
            }
        }catch(SQLException ex){
            //Logger.getLogger(CreationJoueur.class.getName()).log(Level.SEVERE,null,ex);
        }
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 255, 102));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        jButton1.setText("Quitter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caf - Copy.gif"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("effectif complet de l'equipe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        try{
                cb2.removeAllItems();
                EditionDAO editionDAO = new EditionDAO();
                 Edition edition = editionDAO.cherche((String)cb1.getSelectedItem()); 
                EquipeDAO eqDAO = new EquipeDAO();
                ArrayList<Equipe> equipe = new ArrayList<>();
                equipe = eqDAO.chercher(edition.getId());

                for(Equipe eq : equipe){
                     cb2.addItem(eq.getNom());
                }
            }catch(SQLException ex){
                 Logger.getLogger(CreationJoueur.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            EditionDAO editionDAO = new EditionDAO();
            JoueurDAO joueurDAO = new JoueurDAO();
            ArrayList<Joueur> liste_joueur1= joueurDAO.cherche((String)cb2.getSelectedItem(), editionDAO.cherche((String)cb1.getSelectedItem()).getId());
            if(joueurDAO.joueurEquipe((String)cb2.getSelectedItem(), editionDAO.cherche((String)cb1.getSelectedItem()).getId()) == 0){
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null, null, null, null},

                    },
                    new String [] {
                        "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
                    }
                ));
            }
            else if (joueurDAO.joueurEquipe((String)cb2.getSelectedItem(), editionDAO.cherche((String)cb1.getSelectedItem()).getId()) == 23){
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                            {liste_joueur1.get(0).getNom(), liste_joueur1.get(0).getPrenom(), liste_joueur1.get(0).getDateNaiss(), liste_joueur1.get(0).getPoste(), liste_joueur1.get(0).getDossard(), liste_joueur1.get(0).getButsC(), liste_joueur1.get(0).getButsT()},
                            {liste_joueur1.get(1).getNom(), liste_joueur1.get(1).getPrenom(), liste_joueur1.get(1).getDateNaiss(), liste_joueur1.get(1).getPoste(), liste_joueur1.get(1).getDossard(), liste_joueur1.get(1).getButsC(), liste_joueur1.get(1).getButsT()},
                            {liste_joueur1.get(2).getNom(), liste_joueur1.get(2).getPrenom(), liste_joueur1.get(2).getDateNaiss(), liste_joueur1.get(2).getPoste(), liste_joueur1.get(2).getDossard(), liste_joueur1.get(2).getButsC(), liste_joueur1.get(2).getButsT()},
                            {liste_joueur1.get(3).getNom(), liste_joueur1.get(3).getPrenom(), liste_joueur1.get(3).getDateNaiss(), liste_joueur1.get(3).getPoste(), liste_joueur1.get(3).getDossard(), liste_joueur1.get(3).getButsC(), liste_joueur1.get(3).getButsT()},
                            {liste_joueur1.get(4).getNom(), liste_joueur1.get(4).getPrenom(), liste_joueur1.get(4).getDateNaiss(), liste_joueur1.get(4).getPoste(), liste_joueur1.get(4).getDossard(), liste_joueur1.get(4).getButsC(), liste_joueur1.get(4).getButsT()},
                            {liste_joueur1.get(5).getNom(), liste_joueur1.get(5).getPrenom(), liste_joueur1.get(5).getDateNaiss(), liste_joueur1.get(5).getPoste(), liste_joueur1.get(5).getDossard(), liste_joueur1.get(5).getButsC(), liste_joueur1.get(5).getButsT()},
                            {liste_joueur1.get(6).getNom(), liste_joueur1.get(6).getPrenom(), liste_joueur1.get(6).getDateNaiss(), liste_joueur1.get(6).getPoste(), liste_joueur1.get(6).getDossard(), liste_joueur1.get(6).getButsC(), liste_joueur1.get(6).getButsT()},                        
                            {liste_joueur1.get(7).getNom(), liste_joueur1.get(7).getPrenom(), liste_joueur1.get(7).getDateNaiss(), liste_joueur1.get(7).getPoste(), liste_joueur1.get(7).getDossard(), liste_joueur1.get(7).getButsC(), liste_joueur1.get(7).getButsT()},
                            {liste_joueur1.get(8).getNom(), liste_joueur1.get(8).getPrenom(), liste_joueur1.get(8).getDateNaiss(), liste_joueur1.get(8).getPoste(), liste_joueur1.get(8).getDossard(), liste_joueur1.get(8).getButsC(), liste_joueur1.get(8).getButsT()},
                            {liste_joueur1.get(9).getNom(), liste_joueur1.get(9).getPrenom(), liste_joueur1.get(9).getDateNaiss(), liste_joueur1.get(9).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(9).getButsC(), liste_joueur1.get(9).getButsT()},
                            {liste_joueur1.get(10).getNom(), liste_joueur1.get(10).getPrenom(), liste_joueur1.get(10).getDateNaiss(), liste_joueur1.get(10).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(10).getButsC(), liste_joueur1.get(10).getButsT()},
                            {liste_joueur1.get(11).getNom(), liste_joueur1.get(11).getPrenom(), liste_joueur1.get(11).getDateNaiss(), liste_joueur1.get(11).getPoste(), liste_joueur1.get(11).getDossard(), liste_joueur1.get(11).getButsC(), liste_joueur1.get(11).getButsT()},
                            {liste_joueur1.get(12).getNom(), liste_joueur1.get(12).getPrenom(), liste_joueur1.get(12).getDateNaiss(), liste_joueur1.get(12).getPoste(), liste_joueur1.get(12).getDossard(), liste_joueur1.get(12).getButsC(), liste_joueur1.get(12).getButsT()},
                            {liste_joueur1.get(13).getNom(), liste_joueur1.get(13).getPrenom(), liste_joueur1.get(13).getDateNaiss(), liste_joueur1.get(13).getPoste(), liste_joueur1.get(13).getDossard(), liste_joueur1.get(13).getButsC(), liste_joueur1.get(13).getButsT()},
                            {liste_joueur1.get(14).getNom(), liste_joueur1.get(14).getPrenom(), liste_joueur1.get(14).getDateNaiss(), liste_joueur1.get(14).getPoste(), liste_joueur1.get(14).getDossard(), liste_joueur1.get(14).getButsC(), liste_joueur1.get(14).getButsT()},
                            {liste_joueur1.get(15).getNom(), liste_joueur1.get(15).getPrenom(), liste_joueur1.get(15).getDateNaiss(), liste_joueur1.get(15).getPoste(), liste_joueur1.get(15).getDossard(), liste_joueur1.get(15).getButsC(), liste_joueur1.get(15).getButsT()},
                            {liste_joueur1.get(16).getNom(), liste_joueur1.get(16).getPrenom(), liste_joueur1.get(16).getDateNaiss(), liste_joueur1.get(16).getPoste(), liste_joueur1.get(16).getDossard(), liste_joueur1.get(16).getButsC(), liste_joueur1.get(16).getButsT()},
                            {liste_joueur1.get(17).getNom(), liste_joueur1.get(17).getPrenom(), liste_joueur1.get(17).getDateNaiss(), liste_joueur1.get(17).getPoste(), liste_joueur1.get(17).getDossard(), liste_joueur1.get(17).getButsC(), liste_joueur1.get(17).getButsT()},
                            {liste_joueur1.get(18).getNom(), liste_joueur1.get(18).getPrenom(), liste_joueur1.get(18).getDateNaiss(), liste_joueur1.get(18).getPoste(), liste_joueur1.get(18).getDossard(), liste_joueur1.get(18).getButsC(), liste_joueur1.get(18).getButsT()},
                            {liste_joueur1.get(19).getNom(), liste_joueur1.get(19).getPrenom(), liste_joueur1.get(19).getDateNaiss(), liste_joueur1.get(19).getPoste(), liste_joueur1.get(19).getDossard(), liste_joueur1.get(19).getButsC(), liste_joueur1.get(19).getButsT()},
                            {liste_joueur1.get(20).getNom(), liste_joueur1.get(20).getPrenom(), liste_joueur1.get(20).getDateNaiss(), liste_joueur1.get(20).getPoste(), liste_joueur1.get(20).getDossard(), liste_joueur1.get(20).getButsC(), liste_joueur1.get(20).getButsT()},
                            {liste_joueur1.get(21).getNom(), liste_joueur1.get(21).getPrenom(), liste_joueur1.get(21).getDateNaiss(), liste_joueur1.get(21).getPoste(), liste_joueur1.get(21).getDossard(), liste_joueur1.get(21).getButsC(), liste_joueur1.get(21).getButsT()},
                            {liste_joueur1.get(22).getNom(), liste_joueur1.get(22).getPrenom(), liste_joueur1.get(22).getDateNaiss(), liste_joueur1.get(22).getPoste(), liste_joueur1.get(22).getDossard(), liste_joueur1.get(22).getButsC(), liste_joueur1.get(22).getButsT()},
                        },
                        new String [] {
                            "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
                        }
                ) );
            }
            else if(joueurDAO.joueurEquipe((String)cb2.getSelectedItem(), editionDAO.cherche((String)cb1.getSelectedItem()).getId()) == 22){
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                            {liste_joueur1.get(0).getNom(), liste_joueur1.get(0).getPrenom(), liste_joueur1.get(0).getDateNaiss(), liste_joueur1.get(0).getPoste(), liste_joueur1.get(0).getDossard(), liste_joueur1.get(0).getButsC(), liste_joueur1.get(0).getButsT()},
                            {liste_joueur1.get(1).getNom(), liste_joueur1.get(1).getPrenom(), liste_joueur1.get(1).getDateNaiss(), liste_joueur1.get(1).getPoste(), liste_joueur1.get(1).getDossard(), liste_joueur1.get(1).getButsC(), liste_joueur1.get(1).getButsT()},
                            {liste_joueur1.get(2).getNom(), liste_joueur1.get(2).getPrenom(), liste_joueur1.get(2).getDateNaiss(), liste_joueur1.get(2).getPoste(), liste_joueur1.get(2).getDossard(), liste_joueur1.get(2).getButsC(), liste_joueur1.get(2).getButsT()},
                            {liste_joueur1.get(3).getNom(), liste_joueur1.get(3).getPrenom(), liste_joueur1.get(3).getDateNaiss(), liste_joueur1.get(3).getPoste(), liste_joueur1.get(3).getDossard(), liste_joueur1.get(3).getButsC(), liste_joueur1.get(3).getButsT()},
                            {liste_joueur1.get(4).getNom(), liste_joueur1.get(4).getPrenom(), liste_joueur1.get(4).getDateNaiss(), liste_joueur1.get(4).getPoste(), liste_joueur1.get(4).getDossard(), liste_joueur1.get(4).getButsC(), liste_joueur1.get(4).getButsT()},
                            {liste_joueur1.get(5).getNom(), liste_joueur1.get(5).getPrenom(), liste_joueur1.get(5).getDateNaiss(), liste_joueur1.get(5).getPoste(), liste_joueur1.get(5).getDossard(), liste_joueur1.get(5).getButsC(), liste_joueur1.get(5).getButsT()},
                            {liste_joueur1.get(6).getNom(), liste_joueur1.get(6).getPrenom(), liste_joueur1.get(6).getDateNaiss(), liste_joueur1.get(6).getPoste(), liste_joueur1.get(6).getDossard(), liste_joueur1.get(6).getButsC(), liste_joueur1.get(6).getButsT()},                        
                            {liste_joueur1.get(7).getNom(), liste_joueur1.get(7).getPrenom(), liste_joueur1.get(7).getDateNaiss(), liste_joueur1.get(7).getPoste(), liste_joueur1.get(7).getDossard(), liste_joueur1.get(7).getButsC(), liste_joueur1.get(7).getButsT()},
                            {liste_joueur1.get(8).getNom(), liste_joueur1.get(8).getPrenom(), liste_joueur1.get(8).getDateNaiss(), liste_joueur1.get(8).getPoste(), liste_joueur1.get(8).getDossard(), liste_joueur1.get(8).getButsC(), liste_joueur1.get(8).getButsT()},
                            {liste_joueur1.get(9).getNom(), liste_joueur1.get(9).getPrenom(), liste_joueur1.get(9).getDateNaiss(), liste_joueur1.get(9).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(9).getButsC(), liste_joueur1.get(9).getButsT()},
                            {liste_joueur1.get(10).getNom(), liste_joueur1.get(10).getPrenom(), liste_joueur1.get(10).getDateNaiss(), liste_joueur1.get(10).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(10).getButsC(), liste_joueur1.get(10).getButsT()},
                            {liste_joueur1.get(11).getNom(), liste_joueur1.get(11).getPrenom(), liste_joueur1.get(11).getDateNaiss(), liste_joueur1.get(11).getPoste(), liste_joueur1.get(11).getDossard(), liste_joueur1.get(11).getButsC(), liste_joueur1.get(11).getButsT()},
                            {liste_joueur1.get(12).getNom(), liste_joueur1.get(12).getPrenom(), liste_joueur1.get(12).getDateNaiss(), liste_joueur1.get(12).getPoste(), liste_joueur1.get(12).getDossard(), liste_joueur1.get(12).getButsC(), liste_joueur1.get(12).getButsT()},
                            {liste_joueur1.get(13).getNom(), liste_joueur1.get(13).getPrenom(), liste_joueur1.get(13).getDateNaiss(), liste_joueur1.get(13).getPoste(), liste_joueur1.get(13).getDossard(), liste_joueur1.get(13).getButsC(), liste_joueur1.get(13).getButsT()},
                            {liste_joueur1.get(14).getNom(), liste_joueur1.get(14).getPrenom(), liste_joueur1.get(14).getDateNaiss(), liste_joueur1.get(14).getPoste(), liste_joueur1.get(14).getDossard(), liste_joueur1.get(14).getButsC(), liste_joueur1.get(14).getButsT()},
                            {liste_joueur1.get(15).getNom(), liste_joueur1.get(15).getPrenom(), liste_joueur1.get(15).getDateNaiss(), liste_joueur1.get(15).getPoste(), liste_joueur1.get(15).getDossard(), liste_joueur1.get(15).getButsC(), liste_joueur1.get(15).getButsT()},
                            {liste_joueur1.get(16).getNom(), liste_joueur1.get(16).getPrenom(), liste_joueur1.get(16).getDateNaiss(), liste_joueur1.get(16).getPoste(), liste_joueur1.get(16).getDossard(), liste_joueur1.get(16).getButsC(), liste_joueur1.get(16).getButsT()},
                            {liste_joueur1.get(17).getNom(), liste_joueur1.get(17).getPrenom(), liste_joueur1.get(17).getDateNaiss(), liste_joueur1.get(17).getPoste(), liste_joueur1.get(17).getDossard(), liste_joueur1.get(17).getButsC(), liste_joueur1.get(17).getButsT()},
                            {liste_joueur1.get(18).getNom(), liste_joueur1.get(18).getPrenom(), liste_joueur1.get(18).getDateNaiss(), liste_joueur1.get(18).getPoste(), liste_joueur1.get(18).getDossard(), liste_joueur1.get(18).getButsC(), liste_joueur1.get(18).getButsT()},
                            {liste_joueur1.get(19).getNom(), liste_joueur1.get(19).getPrenom(), liste_joueur1.get(19).getDateNaiss(), liste_joueur1.get(19).getPoste(), liste_joueur1.get(19).getDossard(), liste_joueur1.get(19).getButsC(), liste_joueur1.get(19).getButsT()},
                            {liste_joueur1.get(20).getNom(), liste_joueur1.get(20).getPrenom(), liste_joueur1.get(20).getDateNaiss(), liste_joueur1.get(20).getPoste(), liste_joueur1.get(20).getDossard(), liste_joueur1.get(20).getButsC(), liste_joueur1.get(20).getButsT()},
                            {liste_joueur1.get(21).getNom(), liste_joueur1.get(21).getPrenom(), liste_joueur1.get(21).getDateNaiss(), liste_joueur1.get(21).getPoste(), liste_joueur1.get(21).getDossard(), liste_joueur1.get(21).getButsC(), liste_joueur1.get(21).getButsT()},
                            },
                        new String [] {
                            "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
                        }
                ) );
            }
            else if (joueurDAO.joueurEquipe((String)cb2.getSelectedItem(), editionDAO.cherche((String)cb1.getSelectedItem()).getId()) == 21){
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                            {liste_joueur1.get(0).getNom(), liste_joueur1.get(0).getPrenom(), liste_joueur1.get(0).getDateNaiss(), liste_joueur1.get(0).getPoste(), liste_joueur1.get(0).getDossard(), liste_joueur1.get(0).getButsC(), liste_joueur1.get(0).getButsT()},
                            {liste_joueur1.get(1).getNom(), liste_joueur1.get(1).getPrenom(), liste_joueur1.get(1).getDateNaiss(), liste_joueur1.get(1).getPoste(), liste_joueur1.get(1).getDossard(), liste_joueur1.get(1).getButsC(), liste_joueur1.get(1).getButsT()},
                            {liste_joueur1.get(2).getNom(), liste_joueur1.get(2).getPrenom(), liste_joueur1.get(2).getDateNaiss(), liste_joueur1.get(2).getPoste(), liste_joueur1.get(2).getDossard(), liste_joueur1.get(2).getButsC(), liste_joueur1.get(2).getButsT()},
                            {liste_joueur1.get(3).getNom(), liste_joueur1.get(3).getPrenom(), liste_joueur1.get(3).getDateNaiss(), liste_joueur1.get(3).getPoste(), liste_joueur1.get(3).getDossard(), liste_joueur1.get(3).getButsC(), liste_joueur1.get(3).getButsT()},
                            {liste_joueur1.get(4).getNom(), liste_joueur1.get(4).getPrenom(), liste_joueur1.get(4).getDateNaiss(), liste_joueur1.get(4).getPoste(), liste_joueur1.get(4).getDossard(), liste_joueur1.get(4).getButsC(), liste_joueur1.get(4).getButsT()},
                            {liste_joueur1.get(5).getNom(), liste_joueur1.get(5).getPrenom(), liste_joueur1.get(5).getDateNaiss(), liste_joueur1.get(5).getPoste(), liste_joueur1.get(5).getDossard(), liste_joueur1.get(5).getButsC(), liste_joueur1.get(5).getButsT()},
                            {liste_joueur1.get(6).getNom(), liste_joueur1.get(6).getPrenom(), liste_joueur1.get(6).getDateNaiss(), liste_joueur1.get(6).getPoste(), liste_joueur1.get(6).getDossard(), liste_joueur1.get(6).getButsC(), liste_joueur1.get(6).getButsT()},                        
                            {liste_joueur1.get(7).getNom(), liste_joueur1.get(7).getPrenom(), liste_joueur1.get(7).getDateNaiss(), liste_joueur1.get(7).getPoste(), liste_joueur1.get(7).getDossard(), liste_joueur1.get(7).getButsC(), liste_joueur1.get(7).getButsT()},
                            {liste_joueur1.get(8).getNom(), liste_joueur1.get(8).getPrenom(), liste_joueur1.get(8).getDateNaiss(), liste_joueur1.get(8).getPoste(), liste_joueur1.get(8).getDossard(), liste_joueur1.get(8).getButsC(), liste_joueur1.get(8).getButsT()},
                            {liste_joueur1.get(9).getNom(), liste_joueur1.get(9).getPrenom(), liste_joueur1.get(9).getDateNaiss(), liste_joueur1.get(9).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(9).getButsC(), liste_joueur1.get(9).getButsT()},
                            {liste_joueur1.get(10).getNom(), liste_joueur1.get(10).getPrenom(), liste_joueur1.get(10).getDateNaiss(), liste_joueur1.get(10).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(10).getButsC(), liste_joueur1.get(10).getButsT()},
                            {liste_joueur1.get(11).getNom(), liste_joueur1.get(11).getPrenom(), liste_joueur1.get(11).getDateNaiss(), liste_joueur1.get(11).getPoste(), liste_joueur1.get(11).getDossard(), liste_joueur1.get(11).getButsC(), liste_joueur1.get(11).getButsT()},
                            {liste_joueur1.get(12).getNom(), liste_joueur1.get(12).getPrenom(), liste_joueur1.get(12).getDateNaiss(), liste_joueur1.get(12).getPoste(), liste_joueur1.get(12).getDossard(), liste_joueur1.get(12).getButsC(), liste_joueur1.get(12).getButsT()},
                            {liste_joueur1.get(13).getNom(), liste_joueur1.get(13).getPrenom(), liste_joueur1.get(13).getDateNaiss(), liste_joueur1.get(13).getPoste(), liste_joueur1.get(13).getDossard(), liste_joueur1.get(13).getButsC(), liste_joueur1.get(13).getButsT()},
                            {liste_joueur1.get(14).getNom(), liste_joueur1.get(14).getPrenom(), liste_joueur1.get(14).getDateNaiss(), liste_joueur1.get(14).getPoste(), liste_joueur1.get(14).getDossard(), liste_joueur1.get(14).getButsC(), liste_joueur1.get(14).getButsT()},
                            {liste_joueur1.get(15).getNom(), liste_joueur1.get(15).getPrenom(), liste_joueur1.get(15).getDateNaiss(), liste_joueur1.get(15).getPoste(), liste_joueur1.get(15).getDossard(), liste_joueur1.get(15).getButsC(), liste_joueur1.get(15).getButsT()},
                            {liste_joueur1.get(16).getNom(), liste_joueur1.get(16).getPrenom(), liste_joueur1.get(16).getDateNaiss(), liste_joueur1.get(16).getPoste(), liste_joueur1.get(16).getDossard(), liste_joueur1.get(16).getButsC(), liste_joueur1.get(16).getButsT()},
                            {liste_joueur1.get(17).getNom(), liste_joueur1.get(17).getPrenom(), liste_joueur1.get(17).getDateNaiss(), liste_joueur1.get(17).getPoste(), liste_joueur1.get(17).getDossard(), liste_joueur1.get(17).getButsC(), liste_joueur1.get(17).getButsT()},
                            {liste_joueur1.get(18).getNom(), liste_joueur1.get(18).getPrenom(), liste_joueur1.get(18).getDateNaiss(), liste_joueur1.get(18).getPoste(), liste_joueur1.get(18).getDossard(), liste_joueur1.get(18).getButsC(), liste_joueur1.get(18).getButsT()},
                            {liste_joueur1.get(19).getNom(), liste_joueur1.get(19).getPrenom(), liste_joueur1.get(19).getDateNaiss(), liste_joueur1.get(19).getPoste(), liste_joueur1.get(19).getDossard(), liste_joueur1.get(19).getButsC(), liste_joueur1.get(19).getButsT()},
                            {liste_joueur1.get(20).getNom(), liste_joueur1.get(20).getPrenom(), liste_joueur1.get(20).getDateNaiss(), liste_joueur1.get(20).getPoste(), liste_joueur1.get(20).getDossard(), liste_joueur1.get(20).getButsC(), liste_joueur1.get(20).getButsT()},
                            },
                        new String [] {
                            "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
                        }
                ) );
            }
            else {
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                            {liste_joueur1.get(0).getNom(), liste_joueur1.get(0).getPrenom(), liste_joueur1.get(0).getDateNaiss(), liste_joueur1.get(0).getPoste(), liste_joueur1.get(0).getDossard(), liste_joueur1.get(0).getButsC(), liste_joueur1.get(0).getButsT()},
                            {liste_joueur1.get(1).getNom(), liste_joueur1.get(1).getPrenom(), liste_joueur1.get(1).getDateNaiss(), liste_joueur1.get(1).getPoste(), liste_joueur1.get(1).getDossard(), liste_joueur1.get(1).getButsC(), liste_joueur1.get(1).getButsT()},
                            {liste_joueur1.get(2).getNom(), liste_joueur1.get(2).getPrenom(), liste_joueur1.get(2).getDateNaiss(), liste_joueur1.get(2).getPoste(), liste_joueur1.get(2).getDossard(), liste_joueur1.get(2).getButsC(), liste_joueur1.get(2).getButsT()},
                            {liste_joueur1.get(3).getNom(), liste_joueur1.get(3).getPrenom(), liste_joueur1.get(3).getDateNaiss(), liste_joueur1.get(3).getPoste(), liste_joueur1.get(3).getDossard(), liste_joueur1.get(3).getButsC(), liste_joueur1.get(3).getButsT()},
                            {liste_joueur1.get(4).getNom(), liste_joueur1.get(4).getPrenom(), liste_joueur1.get(4).getDateNaiss(), liste_joueur1.get(4).getPoste(), liste_joueur1.get(4).getDossard(), liste_joueur1.get(4).getButsC(), liste_joueur1.get(4).getButsT()},
                            {liste_joueur1.get(5).getNom(), liste_joueur1.get(5).getPrenom(), liste_joueur1.get(5).getDateNaiss(), liste_joueur1.get(5).getPoste(), liste_joueur1.get(5).getDossard(), liste_joueur1.get(5).getButsC(), liste_joueur1.get(5).getButsT()},
                            {liste_joueur1.get(6).getNom(), liste_joueur1.get(6).getPrenom(), liste_joueur1.get(6).getDateNaiss(), liste_joueur1.get(6).getPoste(), liste_joueur1.get(6).getDossard(), liste_joueur1.get(6).getButsC(), liste_joueur1.get(6).getButsT()},                        
                            {liste_joueur1.get(7).getNom(), liste_joueur1.get(7).getPrenom(), liste_joueur1.get(7).getDateNaiss(), liste_joueur1.get(7).getPoste(), liste_joueur1.get(7).getDossard(), liste_joueur1.get(7).getButsC(), liste_joueur1.get(7).getButsT()},
                            {liste_joueur1.get(8).getNom(), liste_joueur1.get(8).getPrenom(), liste_joueur1.get(8).getDateNaiss(), liste_joueur1.get(8).getPoste(), liste_joueur1.get(8).getDossard(), liste_joueur1.get(8).getButsC(), liste_joueur1.get(8).getButsT()},
                            {liste_joueur1.get(9).getNom(), liste_joueur1.get(9).getPrenom(), liste_joueur1.get(9).getDateNaiss(), liste_joueur1.get(9).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(9).getButsC(), liste_joueur1.get(9).getButsT()},
                            {liste_joueur1.get(10).getNom(), liste_joueur1.get(10).getPrenom(), liste_joueur1.get(10).getDateNaiss(), liste_joueur1.get(10).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(10).getButsC(), liste_joueur1.get(10).getButsT()},
                            {liste_joueur1.get(11).getNom(), liste_joueur1.get(11).getPrenom(), liste_joueur1.get(11).getDateNaiss(), liste_joueur1.get(11).getPoste(), liste_joueur1.get(11).getDossard(), liste_joueur1.get(11).getButsC(), liste_joueur1.get(11).getButsT()},
                            {liste_joueur1.get(12).getNom(), liste_joueur1.get(12).getPrenom(), liste_joueur1.get(12).getDateNaiss(), liste_joueur1.get(12).getPoste(), liste_joueur1.get(12).getDossard(), liste_joueur1.get(12).getButsC(), liste_joueur1.get(12).getButsT()},
                            {liste_joueur1.get(13).getNom(), liste_joueur1.get(13).getPrenom(), liste_joueur1.get(13).getDateNaiss(), liste_joueur1.get(13).getPoste(), liste_joueur1.get(13).getDossard(), liste_joueur1.get(13).getButsC(), liste_joueur1.get(13).getButsT()},
                            {liste_joueur1.get(14).getNom(), liste_joueur1.get(14).getPrenom(), liste_joueur1.get(14).getDateNaiss(), liste_joueur1.get(14).getPoste(), liste_joueur1.get(14).getDossard(), liste_joueur1.get(14).getButsC(), liste_joueur1.get(14).getButsT()},
                            {liste_joueur1.get(15).getNom(), liste_joueur1.get(15).getPrenom(), liste_joueur1.get(15).getDateNaiss(), liste_joueur1.get(15).getPoste(), liste_joueur1.get(15).getDossard(), liste_joueur1.get(15).getButsC(), liste_joueur1.get(15).getButsT()},
                            {liste_joueur1.get(16).getNom(), liste_joueur1.get(16).getPrenom(), liste_joueur1.get(16).getDateNaiss(), liste_joueur1.get(16).getPoste(), liste_joueur1.get(16).getDossard(), liste_joueur1.get(16).getButsC(), liste_joueur1.get(16).getButsT()},
                            {liste_joueur1.get(17).getNom(), liste_joueur1.get(17).getPrenom(), liste_joueur1.get(17).getDateNaiss(), liste_joueur1.get(17).getPoste(), liste_joueur1.get(17).getDossard(), liste_joueur1.get(17).getButsC(), liste_joueur1.get(17).getButsT()},
                            {liste_joueur1.get(18).getNom(), liste_joueur1.get(18).getPrenom(), liste_joueur1.get(18).getDateNaiss(), liste_joueur1.get(18).getPoste(), liste_joueur1.get(18).getDossard(), liste_joueur1.get(18).getButsC(), liste_joueur1.get(18).getButsT()},
                            {liste_joueur1.get(19).getNom(), liste_joueur1.get(19).getPrenom(), liste_joueur1.get(19).getDateNaiss(), liste_joueur1.get(19).getPoste(), liste_joueur1.get(19).getDossard(), liste_joueur1.get(19).getButsC(), liste_joueur1.get(19).getButsT()},
                            },
                        new String [] {
                            "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
                        }
                ) );
            }
        } catch (SQLException ex) {
            Logger.getLogger(Fiche_Equipe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cb2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Effectif_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Effectif_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Effectif_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Effectif_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Effectif_Equipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
