/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vue;

import coucheDAO.EditionDAO;
import coucheDAO.EquipeDAO;
import coucheDAO.JoueurDAO;
import edition.Edition;
import equipe.Equipe;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import personnel.Joueur;

/**
 *
 * @author Landry
 */
public class Fiche_Equipe extends javax.swing.JFrame {

    /**
     * Creates new form Fiche_Equipe
     */
    public Fiche_Equipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("Effectif ");

        jLabel1.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        jLabel1.setText("Edition");

        jLabel2.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        jLabel2.setText("Equipe");

        cb1.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        try{
            EditionDAO editionDAO = new EditionDAO();
            ArrayList<Edition> edition = new ArrayList<>();
            edition = editionDAO.trouve();

            for(Edition ed : edition){
                cb1.addItem(ed.getAnnee());
            }
        }catch(SQLException ex){
            //Logger.getLogger(CreationJoueur.class.getName()).log(Level.SEVERE,null,ex);
        }
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        cb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb2MouseClicked(evt);
            }
        });
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Perpetua Titling MT", 2, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},

            },
            new String [] {
                "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(102, 255, 102));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("DigifaceWide", 0, 11)); // NOI18N
        jButton1.setText("Quitter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caf - Copy.gif"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setText("Staff ");

        jLabel6.setFont(new java.awt.Font("DigifaceWide", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Entrainneur");

        jLabel7.setFont(new java.awt.Font("DigifaceWide", 2, 12)); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("DigifaceWide", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Adjoint");

        jLabel9.setFont(new java.awt.Font("DigifaceWide", 2, 12)); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("DigifaceWide", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Entraineur de Gardien");

        jLabel11.setFont(new java.awt.Font("DigifaceWide", 2, 12)); // NOI18N
        jLabel11.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("DigifaceWide", 2, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Medecin");

        jLabel13.setFont(new java.awt.Font("DigifaceWide", 2, 12)); // NOI18N
        jLabel13.setText("jLabel13");

        jLabel14.setFont(new java.awt.Font("DigifaceWide", 2, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("President de Fédération");

        jLabel15.setFont(new java.awt.Font("DigifaceWide", 2, 12)); // NOI18N
        jLabel15.setText("jLabel15");

        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 153, 0));
        jLabel16.setText("Effectif");

        jLabel17.setFont(new java.awt.Font("Perpetua Titling MT", 2, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 51));
        jLabel17.setText("composition complète de l'equipe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jButton1)
                .addGap(97, 97, 97))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                        .addContainerGap())
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(45, 45, 45)
                                                        .addComponent(jLabel7)))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel15)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)))
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        try{
                cb2.removeAllItems();
                EditionDAO editionDAO = new EditionDAO();
                Edition edition = editionDAO.cherche((String)cb1.getSelectedItem()); 
                EquipeDAO eqDAO = new EquipeDAO();
                ArrayList<Equipe> equipe = new ArrayList<>();
                equipe = eqDAO.chercher(edition.getId());

                for(Equipe eq : equipe){
                     cb2.addItem(eq.getNom());
                }
            }catch(SQLException ex){
                 Logger.getLogger(CreationJoueur.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        try {
            // TODO add your handling code here:
            JoueurDAO joueurDAO = new JoueurDAO();
            EditionDAO editionDAO = new EditionDAO();
            ArrayList<Joueur> liste_joueur1= joueurDAO.cherche((String)cb2.getSelectedItem(), editionDAO.cherche((String)cb1.getSelectedItem()).getId());
            if(joueurDAO.joueurEquipe((String)cb2.getSelectedItem(), editionDAO.cherche((String)cb1.getSelectedItem()).getId()) == 0){
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null, null, null, null},

                    },
                    new String [] {
                        "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
                    }
                ));
            }
            else if (joueurDAO.joueurEquipe((String)cb2.getSelectedItem(), editionDAO.cherche((String)cb1.getSelectedItem()).getId()) == 23){
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                            {liste_joueur1.get(0).getNom(), liste_joueur1.get(0).getPrenom(), liste_joueur1.get(0).getDateNaiss(), liste_joueur1.get(0).getPoste(), liste_joueur1.get(0).getDossard(), liste_joueur1.get(0).getButsC(), liste_joueur1.get(0).getButsT()},
                            {liste_joueur1.get(1).getNom(), liste_joueur1.get(1).getPrenom(), liste_joueur1.get(1).getDateNaiss(), liste_joueur1.get(1).getPoste(), liste_joueur1.get(1).getDossard(), liste_joueur1.get(1).getButsC(), liste_joueur1.get(1).getButsT()},
                            {liste_joueur1.get(2).getNom(), liste_joueur1.get(2).getPrenom(), liste_joueur1.get(2).getDateNaiss(), liste_joueur1.get(2).getPoste(), liste_joueur1.get(2).getDossard(), liste_joueur1.get(2).getButsC(), liste_joueur1.get(2).getButsT()},
                            {liste_joueur1.get(3).getNom(), liste_joueur1.get(3).getPrenom(), liste_joueur1.get(3).getDateNaiss(), liste_joueur1.get(3).getPoste(), liste_joueur1.get(3).getDossard(), liste_joueur1.get(3).getButsC(), liste_joueur1.get(3).getButsT()},
                            {liste_joueur1.get(4).getNom(), liste_joueur1.get(4).getPrenom(), liste_joueur1.get(4).getDateNaiss(), liste_joueur1.get(4).getPoste(), liste_joueur1.get(4).getDossard(), liste_joueur1.get(4).getButsC(), liste_joueur1.get(4).getButsT()},
                            {liste_joueur1.get(5).getNom(), liste_joueur1.get(5).getPrenom(), liste_joueur1.get(5).getDateNaiss(), liste_joueur1.get(5).getPoste(), liste_joueur1.get(5).getDossard(), liste_joueur1.get(5).getButsC(), liste_joueur1.get(5).getButsT()},
                            {liste_joueur1.get(6).getNom(), liste_joueur1.get(6).getPrenom(), liste_joueur1.get(6).getDateNaiss(), liste_joueur1.get(6).getPoste(), liste_joueur1.get(6).getDossard(), liste_joueur1.get(6).getButsC(), liste_joueur1.get(6).getButsT()},                        
                            {liste_joueur1.get(7).getNom(), liste_joueur1.get(7).getPrenom(), liste_joueur1.get(7).getDateNaiss(), liste_joueur1.get(7).getPoste(), liste_joueur1.get(7).getDossard(), liste_joueur1.get(7).getButsC(), liste_joueur1.get(7).getButsT()},
                            {liste_joueur1.get(8).getNom(), liste_joueur1.get(8).getPrenom(), liste_joueur1.get(8).getDateNaiss(), liste_joueur1.get(8).getPoste(), liste_joueur1.get(8).getDossard(), liste_joueur1.get(8).getButsC(), liste_joueur1.get(8).getButsT()},
                            {liste_joueur1.get(9).getNom(), liste_joueur1.get(9).getPrenom(), liste_joueur1.get(9).getDateNaiss(), liste_joueur1.get(9).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(9).getButsC(), liste_joueur1.get(9).getButsT()},
                            {liste_joueur1.get(10).getNom(), liste_joueur1.get(10).getPrenom(), liste_joueur1.get(10).getDateNaiss(), liste_joueur1.get(10).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(10).getButsC(), liste_joueur1.get(10).getButsT()},
                            {liste_joueur1.get(11).getNom(), liste_joueur1.get(11).getPrenom(), liste_joueur1.get(11).getDateNaiss(), liste_joueur1.get(11).getPoste(), liste_joueur1.get(11).getDossard(), liste_joueur1.get(11).getButsC(), liste_joueur1.get(11).getButsT()},
                            {liste_joueur1.get(12).getNom(), liste_joueur1.get(12).getPrenom(), liste_joueur1.get(12).getDateNaiss(), liste_joueur1.get(12).getPoste(), liste_joueur1.get(12).getDossard(), liste_joueur1.get(12).getButsC(), liste_joueur1.get(12).getButsT()},
                            {liste_joueur1.get(13).getNom(), liste_joueur1.get(13).getPrenom(), liste_joueur1.get(13).getDateNaiss(), liste_joueur1.get(13).getPoste(), liste_joueur1.get(13).getDossard(), liste_joueur1.get(13).getButsC(), liste_joueur1.get(13).getButsT()},
                            {liste_joueur1.get(14).getNom(), liste_joueur1.get(14).getPrenom(), liste_joueur1.get(14).getDateNaiss(), liste_joueur1.get(14).getPoste(), liste_joueur1.get(14).getDossard(), liste_joueur1.get(14).getButsC(), liste_joueur1.get(14).getButsT()},
                            {liste_joueur1.get(15).getNom(), liste_joueur1.get(15).getPrenom(), liste_joueur1.get(15).getDateNaiss(), liste_joueur1.get(15).getPoste(), liste_joueur1.get(15).getDossard(), liste_joueur1.get(15).getButsC(), liste_joueur1.get(15).getButsT()},
                            {liste_joueur1.get(16).getNom(), liste_joueur1.get(16).getPrenom(), liste_joueur1.get(16).getDateNaiss(), liste_joueur1.get(16).getPoste(), liste_joueur1.get(16).getDossard(), liste_joueur1.get(16).getButsC(), liste_joueur1.get(16).getButsT()},
                            {liste_joueur1.get(17).getNom(), liste_joueur1.get(17).getPrenom(), liste_joueur1.get(17).getDateNaiss(), liste_joueur1.get(17).getPoste(), liste_joueur1.get(17).getDossard(), liste_joueur1.get(17).getButsC(), liste_joueur1.get(17).getButsT()},
                            {liste_joueur1.get(18).getNom(), liste_joueur1.get(18).getPrenom(), liste_joueur1.get(18).getDateNaiss(), liste_joueur1.get(18).getPoste(), liste_joueur1.get(18).getDossard(), liste_joueur1.get(18).getButsC(), liste_joueur1.get(18).getButsT()},
                            {liste_joueur1.get(19).getNom(), liste_joueur1.get(19).getPrenom(), liste_joueur1.get(19).getDateNaiss(), liste_joueur1.get(19).getPoste(), liste_joueur1.get(19).getDossard(), liste_joueur1.get(19).getButsC(), liste_joueur1.get(19).getButsT()},
                            {liste_joueur1.get(20).getNom(), liste_joueur1.get(20).getPrenom(), liste_joueur1.get(20).getDateNaiss(), liste_joueur1.get(20).getPoste(), liste_joueur1.get(20).getDossard(), liste_joueur1.get(20).getButsC(), liste_joueur1.get(20).getButsT()},
                            {liste_joueur1.get(21).getNom(), liste_joueur1.get(21).getPrenom(), liste_joueur1.get(21).getDateNaiss(), liste_joueur1.get(21).getPoste(), liste_joueur1.get(21).getDossard(), liste_joueur1.get(21).getButsC(), liste_joueur1.get(21).getButsT()},
                            {liste_joueur1.get(22).getNom(), liste_joueur1.get(22).getPrenom(), liste_joueur1.get(22).getDateNaiss(), liste_joueur1.get(22).getPoste(), liste_joueur1.get(22).getDossard(), liste_joueur1.get(22).getButsC(), liste_joueur1.get(22).getButsT()},
                        },
                        new String [] {
                            "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
                        }
                ) );
            }
            else if(joueurDAO.joueurEquipe((String)cb2.getSelectedItem(), editionDAO.cherche((String)cb1.getSelectedItem()).getId()) == 22){
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                            {liste_joueur1.get(0).getNom(), liste_joueur1.get(0).getPrenom(), liste_joueur1.get(0).getDateNaiss(), liste_joueur1.get(0).getPoste(), liste_joueur1.get(0).getDossard(), liste_joueur1.get(0).getButsC(), liste_joueur1.get(0).getButsT()},
                            {liste_joueur1.get(1).getNom(), liste_joueur1.get(1).getPrenom(), liste_joueur1.get(1).getDateNaiss(), liste_joueur1.get(1).getPoste(), liste_joueur1.get(1).getDossard(), liste_joueur1.get(1).getButsC(), liste_joueur1.get(1).getButsT()},
                            {liste_joueur1.get(2).getNom(), liste_joueur1.get(2).getPrenom(), liste_joueur1.get(2).getDateNaiss(), liste_joueur1.get(2).getPoste(), liste_joueur1.get(2).getDossard(), liste_joueur1.get(2).getButsC(), liste_joueur1.get(2).getButsT()},
                            {liste_joueur1.get(3).getNom(), liste_joueur1.get(3).getPrenom(), liste_joueur1.get(3).getDateNaiss(), liste_joueur1.get(3).getPoste(), liste_joueur1.get(3).getDossard(), liste_joueur1.get(3).getButsC(), liste_joueur1.get(3).getButsT()},
                            {liste_joueur1.get(4).getNom(), liste_joueur1.get(4).getPrenom(), liste_joueur1.get(4).getDateNaiss(), liste_joueur1.get(4).getPoste(), liste_joueur1.get(4).getDossard(), liste_joueur1.get(4).getButsC(), liste_joueur1.get(4).getButsT()},
                            {liste_joueur1.get(5).getNom(), liste_joueur1.get(5).getPrenom(), liste_joueur1.get(5).getDateNaiss(), liste_joueur1.get(5).getPoste(), liste_joueur1.get(5).getDossard(), liste_joueur1.get(5).getButsC(), liste_joueur1.get(5).getButsT()},
                            {liste_joueur1.get(6).getNom(), liste_joueur1.get(6).getPrenom(), liste_joueur1.get(6).getDateNaiss(), liste_joueur1.get(6).getPoste(), liste_joueur1.get(6).getDossard(), liste_joueur1.get(6).getButsC(), liste_joueur1.get(6).getButsT()},                        
                            {liste_joueur1.get(7).getNom(), liste_joueur1.get(7).getPrenom(), liste_joueur1.get(7).getDateNaiss(), liste_joueur1.get(7).getPoste(), liste_joueur1.get(7).getDossard(), liste_joueur1.get(7).getButsC(), liste_joueur1.get(7).getButsT()},
                            {liste_joueur1.get(8).getNom(), liste_joueur1.get(8).getPrenom(), liste_joueur1.get(8).getDateNaiss(), liste_joueur1.get(8).getPoste(), liste_joueur1.get(8).getDossard(), liste_joueur1.get(8).getButsC(), liste_joueur1.get(8).getButsT()},
                            {liste_joueur1.get(9).getNom(), liste_joueur1.get(9).getPrenom(), liste_joueur1.get(9).getDateNaiss(), liste_joueur1.get(9).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(9).getButsC(), liste_joueur1.get(9).getButsT()},
                            {liste_joueur1.get(10).getNom(), liste_joueur1.get(10).getPrenom(), liste_joueur1.get(10).getDateNaiss(), liste_joueur1.get(10).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(10).getButsC(), liste_joueur1.get(10).getButsT()},
                            {liste_joueur1.get(11).getNom(), liste_joueur1.get(11).getPrenom(), liste_joueur1.get(11).getDateNaiss(), liste_joueur1.get(11).getPoste(), liste_joueur1.get(11).getDossard(), liste_joueur1.get(11).getButsC(), liste_joueur1.get(11).getButsT()},
                            {liste_joueur1.get(12).getNom(), liste_joueur1.get(12).getPrenom(), liste_joueur1.get(12).getDateNaiss(), liste_joueur1.get(12).getPoste(), liste_joueur1.get(12).getDossard(), liste_joueur1.get(12).getButsC(), liste_joueur1.get(12).getButsT()},
                            {liste_joueur1.get(13).getNom(), liste_joueur1.get(13).getPrenom(), liste_joueur1.get(13).getDateNaiss(), liste_joueur1.get(13).getPoste(), liste_joueur1.get(13).getDossard(), liste_joueur1.get(13).getButsC(), liste_joueur1.get(13).getButsT()},
                            {liste_joueur1.get(14).getNom(), liste_joueur1.get(14).getPrenom(), liste_joueur1.get(14).getDateNaiss(), liste_joueur1.get(14).getPoste(), liste_joueur1.get(14).getDossard(), liste_joueur1.get(14).getButsC(), liste_joueur1.get(14).getButsT()},
                            {liste_joueur1.get(15).getNom(), liste_joueur1.get(15).getPrenom(), liste_joueur1.get(15).getDateNaiss(), liste_joueur1.get(15).getPoste(), liste_joueur1.get(15).getDossard(), liste_joueur1.get(15).getButsC(), liste_joueur1.get(15).getButsT()},
                            {liste_joueur1.get(16).getNom(), liste_joueur1.get(16).getPrenom(), liste_joueur1.get(16).getDateNaiss(), liste_joueur1.get(16).getPoste(), liste_joueur1.get(16).getDossard(), liste_joueur1.get(16).getButsC(), liste_joueur1.get(16).getButsT()},
                            {liste_joueur1.get(17).getNom(), liste_joueur1.get(17).getPrenom(), liste_joueur1.get(17).getDateNaiss(), liste_joueur1.get(17).getPoste(), liste_joueur1.get(17).getDossard(), liste_joueur1.get(17).getButsC(), liste_joueur1.get(17).getButsT()},
                            {liste_joueur1.get(18).getNom(), liste_joueur1.get(18).getPrenom(), liste_joueur1.get(18).getDateNaiss(), liste_joueur1.get(18).getPoste(), liste_joueur1.get(18).getDossard(), liste_joueur1.get(18).getButsC(), liste_joueur1.get(18).getButsT()},
                            {liste_joueur1.get(19).getNom(), liste_joueur1.get(19).getPrenom(), liste_joueur1.get(19).getDateNaiss(), liste_joueur1.get(19).getPoste(), liste_joueur1.get(19).getDossard(), liste_joueur1.get(19).getButsC(), liste_joueur1.get(19).getButsT()},
                            {liste_joueur1.get(20).getNom(), liste_joueur1.get(20).getPrenom(), liste_joueur1.get(20).getDateNaiss(), liste_joueur1.get(20).getPoste(), liste_joueur1.get(20).getDossard(), liste_joueur1.get(20).getButsC(), liste_joueur1.get(20).getButsT()},
                            {liste_joueur1.get(21).getNom(), liste_joueur1.get(21).getPrenom(), liste_joueur1.get(21).getDateNaiss(), liste_joueur1.get(21).getPoste(), liste_joueur1.get(21).getDossard(), liste_joueur1.get(21).getButsC(), liste_joueur1.get(21).getButsT()},
                            },
                        new String [] {
                            "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
                        }
                ) );
            }
            else if (joueurDAO.joueurEquipe((String)cb2.getSelectedItem(), editionDAO.cherche((String)cb1.getSelectedItem()).getId()) == 21){
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                            {liste_joueur1.get(0).getNom(), liste_joueur1.get(0).getPrenom(), liste_joueur1.get(0).getDateNaiss(), liste_joueur1.get(0).getPoste(), liste_joueur1.get(0).getDossard(), liste_joueur1.get(0).getButsC(), liste_joueur1.get(0).getButsT()},
                            {liste_joueur1.get(1).getNom(), liste_joueur1.get(1).getPrenom(), liste_joueur1.get(1).getDateNaiss(), liste_joueur1.get(1).getPoste(), liste_joueur1.get(1).getDossard(), liste_joueur1.get(1).getButsC(), liste_joueur1.get(1).getButsT()},
                            {liste_joueur1.get(2).getNom(), liste_joueur1.get(2).getPrenom(), liste_joueur1.get(2).getDateNaiss(), liste_joueur1.get(2).getPoste(), liste_joueur1.get(2).getDossard(), liste_joueur1.get(2).getButsC(), liste_joueur1.get(2).getButsT()},
                            {liste_joueur1.get(3).getNom(), liste_joueur1.get(3).getPrenom(), liste_joueur1.get(3).getDateNaiss(), liste_joueur1.get(3).getPoste(), liste_joueur1.get(3).getDossard(), liste_joueur1.get(3).getButsC(), liste_joueur1.get(3).getButsT()},
                            {liste_joueur1.get(4).getNom(), liste_joueur1.get(4).getPrenom(), liste_joueur1.get(4).getDateNaiss(), liste_joueur1.get(4).getPoste(), liste_joueur1.get(4).getDossard(), liste_joueur1.get(4).getButsC(), liste_joueur1.get(4).getButsT()},
                            {liste_joueur1.get(5).getNom(), liste_joueur1.get(5).getPrenom(), liste_joueur1.get(5).getDateNaiss(), liste_joueur1.get(5).getPoste(), liste_joueur1.get(5).getDossard(), liste_joueur1.get(5).getButsC(), liste_joueur1.get(5).getButsT()},
                            {liste_joueur1.get(6).getNom(), liste_joueur1.get(6).getPrenom(), liste_joueur1.get(6).getDateNaiss(), liste_joueur1.get(6).getPoste(), liste_joueur1.get(6).getDossard(), liste_joueur1.get(6).getButsC(), liste_joueur1.get(6).getButsT()},                        
                            {liste_joueur1.get(7).getNom(), liste_joueur1.get(7).getPrenom(), liste_joueur1.get(7).getDateNaiss(), liste_joueur1.get(7).getPoste(), liste_joueur1.get(7).getDossard(), liste_joueur1.get(7).getButsC(), liste_joueur1.get(7).getButsT()},
                            {liste_joueur1.get(8).getNom(), liste_joueur1.get(8).getPrenom(), liste_joueur1.get(8).getDateNaiss(), liste_joueur1.get(8).getPoste(), liste_joueur1.get(8).getDossard(), liste_joueur1.get(8).getButsC(), liste_joueur1.get(8).getButsT()},
                            {liste_joueur1.get(9).getNom(), liste_joueur1.get(9).getPrenom(), liste_joueur1.get(9).getDateNaiss(), liste_joueur1.get(9).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(9).getButsC(), liste_joueur1.get(9).getButsT()},
                            {liste_joueur1.get(10).getNom(), liste_joueur1.get(10).getPrenom(), liste_joueur1.get(10).getDateNaiss(), liste_joueur1.get(10).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(10).getButsC(), liste_joueur1.get(10).getButsT()},
                            {liste_joueur1.get(11).getNom(), liste_joueur1.get(11).getPrenom(), liste_joueur1.get(11).getDateNaiss(), liste_joueur1.get(11).getPoste(), liste_joueur1.get(11).getDossard(), liste_joueur1.get(11).getButsC(), liste_joueur1.get(11).getButsT()},
                            {liste_joueur1.get(12).getNom(), liste_joueur1.get(12).getPrenom(), liste_joueur1.get(12).getDateNaiss(), liste_joueur1.get(12).getPoste(), liste_joueur1.get(12).getDossard(), liste_joueur1.get(12).getButsC(), liste_joueur1.get(12).getButsT()},
                            {liste_joueur1.get(13).getNom(), liste_joueur1.get(13).getPrenom(), liste_joueur1.get(13).getDateNaiss(), liste_joueur1.get(13).getPoste(), liste_joueur1.get(13).getDossard(), liste_joueur1.get(13).getButsC(), liste_joueur1.get(13).getButsT()},
                            {liste_joueur1.get(14).getNom(), liste_joueur1.get(14).getPrenom(), liste_joueur1.get(14).getDateNaiss(), liste_joueur1.get(14).getPoste(), liste_joueur1.get(14).getDossard(), liste_joueur1.get(14).getButsC(), liste_joueur1.get(14).getButsT()},
                            {liste_joueur1.get(15).getNom(), liste_joueur1.get(15).getPrenom(), liste_joueur1.get(15).getDateNaiss(), liste_joueur1.get(15).getPoste(), liste_joueur1.get(15).getDossard(), liste_joueur1.get(15).getButsC(), liste_joueur1.get(15).getButsT()},
                            {liste_joueur1.get(16).getNom(), liste_joueur1.get(16).getPrenom(), liste_joueur1.get(16).getDateNaiss(), liste_joueur1.get(16).getPoste(), liste_joueur1.get(16).getDossard(), liste_joueur1.get(16).getButsC(), liste_joueur1.get(16).getButsT()},
                            {liste_joueur1.get(17).getNom(), liste_joueur1.get(17).getPrenom(), liste_joueur1.get(17).getDateNaiss(), liste_joueur1.get(17).getPoste(), liste_joueur1.get(17).getDossard(), liste_joueur1.get(17).getButsC(), liste_joueur1.get(17).getButsT()},
                            {liste_joueur1.get(18).getNom(), liste_joueur1.get(18).getPrenom(), liste_joueur1.get(18).getDateNaiss(), liste_joueur1.get(18).getPoste(), liste_joueur1.get(18).getDossard(), liste_joueur1.get(18).getButsC(), liste_joueur1.get(18).getButsT()},
                            {liste_joueur1.get(19).getNom(), liste_joueur1.get(19).getPrenom(), liste_joueur1.get(19).getDateNaiss(), liste_joueur1.get(19).getPoste(), liste_joueur1.get(19).getDossard(), liste_joueur1.get(19).getButsC(), liste_joueur1.get(19).getButsT()},
                            {liste_joueur1.get(20).getNom(), liste_joueur1.get(20).getPrenom(), liste_joueur1.get(20).getDateNaiss(), liste_joueur1.get(20).getPoste(), liste_joueur1.get(20).getDossard(), liste_joueur1.get(20).getButsC(), liste_joueur1.get(20).getButsT()},
                            },
                        new String [] {
                            "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
                        }
                ) );
            }
            else {
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                            {liste_joueur1.get(0).getNom(), liste_joueur1.get(0).getPrenom(), liste_joueur1.get(0).getDateNaiss(), liste_joueur1.get(0).getPoste(), liste_joueur1.get(0).getDossard(), liste_joueur1.get(0).getButsC(), liste_joueur1.get(0).getButsT()},
                            {liste_joueur1.get(1).getNom(), liste_joueur1.get(1).getPrenom(), liste_joueur1.get(1).getDateNaiss(), liste_joueur1.get(1).getPoste(), liste_joueur1.get(1).getDossard(), liste_joueur1.get(1).getButsC(), liste_joueur1.get(1).getButsT()},
                            {liste_joueur1.get(2).getNom(), liste_joueur1.get(2).getPrenom(), liste_joueur1.get(2).getDateNaiss(), liste_joueur1.get(2).getPoste(), liste_joueur1.get(2).getDossard(), liste_joueur1.get(2).getButsC(), liste_joueur1.get(2).getButsT()},
                            {liste_joueur1.get(3).getNom(), liste_joueur1.get(3).getPrenom(), liste_joueur1.get(3).getDateNaiss(), liste_joueur1.get(3).getPoste(), liste_joueur1.get(3).getDossard(), liste_joueur1.get(3).getButsC(), liste_joueur1.get(3).getButsT()},
                            {liste_joueur1.get(4).getNom(), liste_joueur1.get(4).getPrenom(), liste_joueur1.get(4).getDateNaiss(), liste_joueur1.get(4).getPoste(), liste_joueur1.get(4).getDossard(), liste_joueur1.get(4).getButsC(), liste_joueur1.get(4).getButsT()},
                            {liste_joueur1.get(5).getNom(), liste_joueur1.get(5).getPrenom(), liste_joueur1.get(5).getDateNaiss(), liste_joueur1.get(5).getPoste(), liste_joueur1.get(5).getDossard(), liste_joueur1.get(5).getButsC(), liste_joueur1.get(5).getButsT()},
                            {liste_joueur1.get(6).getNom(), liste_joueur1.get(6).getPrenom(), liste_joueur1.get(6).getDateNaiss(), liste_joueur1.get(6).getPoste(), liste_joueur1.get(6).getDossard(), liste_joueur1.get(6).getButsC(), liste_joueur1.get(6).getButsT()},                        
                            {liste_joueur1.get(7).getNom(), liste_joueur1.get(7).getPrenom(), liste_joueur1.get(7).getDateNaiss(), liste_joueur1.get(7).getPoste(), liste_joueur1.get(7).getDossard(), liste_joueur1.get(7).getButsC(), liste_joueur1.get(7).getButsT()},
                            {liste_joueur1.get(8).getNom(), liste_joueur1.get(8).getPrenom(), liste_joueur1.get(8).getDateNaiss(), liste_joueur1.get(8).getPoste(), liste_joueur1.get(8).getDossard(), liste_joueur1.get(8).getButsC(), liste_joueur1.get(8).getButsT()},
                            {liste_joueur1.get(9).getNom(), liste_joueur1.get(9).getPrenom(), liste_joueur1.get(9).getDateNaiss(), liste_joueur1.get(9).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(9).getButsC(), liste_joueur1.get(9).getButsT()},
                            {liste_joueur1.get(10).getNom(), liste_joueur1.get(10).getPrenom(), liste_joueur1.get(10).getDateNaiss(), liste_joueur1.get(10).getPoste(), liste_joueur1.get(9).getDossard(), liste_joueur1.get(10).getButsC(), liste_joueur1.get(10).getButsT()},
                            {liste_joueur1.get(11).getNom(), liste_joueur1.get(11).getPrenom(), liste_joueur1.get(11).getDateNaiss(), liste_joueur1.get(11).getPoste(), liste_joueur1.get(11).getDossard(), liste_joueur1.get(11).getButsC(), liste_joueur1.get(11).getButsT()},
                            {liste_joueur1.get(12).getNom(), liste_joueur1.get(12).getPrenom(), liste_joueur1.get(12).getDateNaiss(), liste_joueur1.get(12).getPoste(), liste_joueur1.get(12).getDossard(), liste_joueur1.get(12).getButsC(), liste_joueur1.get(12).getButsT()},
                            {liste_joueur1.get(13).getNom(), liste_joueur1.get(13).getPrenom(), liste_joueur1.get(13).getDateNaiss(), liste_joueur1.get(13).getPoste(), liste_joueur1.get(13).getDossard(), liste_joueur1.get(13).getButsC(), liste_joueur1.get(13).getButsT()},
                            {liste_joueur1.get(14).getNom(), liste_joueur1.get(14).getPrenom(), liste_joueur1.get(14).getDateNaiss(), liste_joueur1.get(14).getPoste(), liste_joueur1.get(14).getDossard(), liste_joueur1.get(14).getButsC(), liste_joueur1.get(14).getButsT()},
                            {liste_joueur1.get(15).getNom(), liste_joueur1.get(15).getPrenom(), liste_joueur1.get(15).getDateNaiss(), liste_joueur1.get(15).getPoste(), liste_joueur1.get(15).getDossard(), liste_joueur1.get(15).getButsC(), liste_joueur1.get(15).getButsT()},
                            {liste_joueur1.get(16).getNom(), liste_joueur1.get(16).getPrenom(), liste_joueur1.get(16).getDateNaiss(), liste_joueur1.get(16).getPoste(), liste_joueur1.get(16).getDossard(), liste_joueur1.get(16).getButsC(), liste_joueur1.get(16).getButsT()},
                            {liste_joueur1.get(17).getNom(), liste_joueur1.get(17).getPrenom(), liste_joueur1.get(17).getDateNaiss(), liste_joueur1.get(17).getPoste(), liste_joueur1.get(17).getDossard(), liste_joueur1.get(17).getButsC(), liste_joueur1.get(17).getButsT()},
                            {liste_joueur1.get(18).getNom(), liste_joueur1.get(18).getPrenom(), liste_joueur1.get(18).getDateNaiss(), liste_joueur1.get(18).getPoste(), liste_joueur1.get(18).getDossard(), liste_joueur1.get(18).getButsC(), liste_joueur1.get(18).getButsT()},
                            {liste_joueur1.get(19).getNom(), liste_joueur1.get(19).getPrenom(), liste_joueur1.get(19).getDateNaiss(), liste_joueur1.get(19).getPoste(), liste_joueur1.get(19).getDossard(), liste_joueur1.get(19).getButsC(), liste_joueur1.get(19).getButsT()},
                            },
                        new String [] {
                            "Nom", "Prenom", "Date de naissance", "Poste", "Dossard", "But de la competition", "But total"
                        }
                ) );
            };
        } catch (SQLException ex) {
            Logger.getLogger(Fiche_Equipe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fiche_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fiche_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fiche_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fiche_Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fiche_Equipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
